### ISSUE TITLE
Question: Get File ID from Name

### ISSUE THREAD

**Issue by Kryptiique** [Backblaze/b2-sdk-python#122] opened 2020-05-07 13:16 UTC
Hi,

I've noticed a lot of the file operations in the SDK take the ID of the file in order to work. Unfortunately, I am only keeping track of the file names locally. How would I go about getting the ID of a file given its name?

Thanks in advance.

**Comment by ppolewicz** [comment] 2020-05-08 00:59
This is by design, because there can be multiple files with the same name stored in the cloud. You can use [b2sdk.v1.Bucket.list_file_versions](https://b2-sdk-python.readthedocs.io/en/master/api/bucket.html#b2sdk.v1.Bucket.list_file_versions) (recently added, about to be released) to get the list of file ids for the given file name.

**Comment by Kryptiique** [comment] 2020-05-11 17:42
I see, that makes sense. What version is this available in?

**Comment by ppolewicz** [comment] 2020-05-12 14:46
It was not released yet. It will be released in the next version which should be a week or two away.
You should be able to already use it if you install the current version from master (but then please switch to a numbered release when we actually release it).

**Closed** 2020-05-26 15:11 UTC
Labels: more-information-needed, question
