### ISSUE TITLE
Duplicity with b2sdk error

### ISSUE THREAD

**Issue by jackreid** [Backblaze/b2-sdk-python#265] opened 2021-06-13 04:19 UTC
It is possible this is an issue on Duplicity's end, not b2sdk, but I thought that I would raise it here and see if anyone would help me narrow it down.

I recently upgraded to Ubuntu 21.04 started getting an error with using Duplicity with B2.

Duplicity is version 0.8.17
b2 is version 2.5.0
b2sdk is 1.9.0

Each seems to work individually. When I try to run a simple test backup, the following happens

`duplicity test.png b2://xxxxxx:xxxxxxxxxx@my-bucket`
`BackendException: B2 backend requires B2 Python SDK (pip install b2sdk)`

I have tried removing and reinstalling each of Duplicity, b2, and b2sdk. If there are things I should investigate to shed light on this, let me know and I will respond promptly.

**Comment by ppolewicz** [comment] 2021-06-13 21:14
duplicate of https://github.com/Backblaze/b2-sdk-python/issues/251

**Closed** 2021-06-27 22:08 UTC
Labels: duplicate, more-information-needed
