### ISSUE TITLE
b2sdk v1.8.0 b2backends.py file is missing the get_minimum_part_size function

### ISSUE THREAD

**Issue by whistl034** [Backblaze/b2-sdk-python#252] opened 2021-05-23 20:00 UTC
I recently installed a CentOS 8.3 VM, and ran into a problem with b2sdk and the duplicity backup program.

- CentOS 8.3 (Digital Ocean std distro, yum update has been run)
- EPEL repos enabled (installed from centos repos via sudo yum install epel-release)
- duplicity 0.8.19 (installed from epel repo via sudo yum install duplicity)
- b2sdk 1.8.0 (installed via sudo /usr/bin/python3 -m pip install b2sdk)

I backup my disk by running:

 `  sudo /usr/bin/duplicity full  -vinfo --asynchronous-upload --volsize 1024 --exclude /dev --exclude /mnt --exclude /proc --exclude /root/.cache --exclude /run --exclude /sys --exclude /tmp / "b2://$B2_ID:$B2_KEY@$B2_BUCKET/"`

The program quickly crashes with return code 30 and a long Python stack trace ending with:

 ```
 File "/usr/local/lib/python3.6/site-packages/duplicity/backends/b2backend.py", line 107, in __init__
    (self.path, bucket_name, self.service.account_info.get_minimum_part_size()), log.INFO)
 AttributeError: 'InMemoryAccountInfo' object has no attribute 'get_minimum_part_size'
```
 
I investigated the issue, and found that the version 1.8.0 of b2sdk in file /usr/local/lib/python3.6/site-packages/b2sdk/account_info/in_memory.py indeed does not have a get_minimum_part_size() function.

Because Python 3.6 is very old, I first tried installing the latest Python 3.9.5 from source, and ran into the exact same issue.

I then found two workarounds:

1) Modify the duplicity file /usr/lib64/python3.6/site-packages/duplicity/backends/b2backend.py to change the single call from "get_minimum_part_size" to "get_absolute_minimum_part_size". It's only used in a logger call, so it doesn't affect the functionality of the software at all.

2) Uninstall b2sdk v1.8.0 (sudo /usr/bin/python3 -m pip uninstall b2sdk) and install b2sdk v1.6.0 (sudo /usr/bin/python3 -m pip install b2sdk==1.6.0). In this case, duplicity works unmodified.

The api documentation states that minor version updates are intended to be backwards compatible, but this function was clearly removed between 1.6.0 and 1.8.0, thus breaking Duplicity v0.8.19's b2 backend.

Thank you for producing this extremely useful package, and I hope this was only an oversight and can result in a simple fix.

Patrick Wolfe

**Comment by ppolewicz** [comment] 2021-05-23 22:17
Duplicate of #251 - bug in duplicity, where they are still using the old interface from b2sdk 0.x.y. That interface was dropped in b2sdk 1.x.y, but still kept working to some extent (that's why they didn't notice until now).

They should change their imports to import things from `b2sdk.v0` or `b2sdk.v1` - importing things from `b2sdk` directly is clearly documented as internal interface. It will change.

**Closed by ppolewicz** 2021-05-23 22:17 UTC
Labels: duplicate
