### ISSUE TITLE
cannot import name 'FileVersionInfoFactory'

### ISSUE THREAD

**Issue by winningindustries** [Backblaze/b2-sdk-python#262] opened 2021-06-09 13:56 UTC
Error after running duplicity 0.8.17-1+b1 (debian testing apt) combined with b2  (all python3)

b2 V 2.5 + b2sdk V 1.9 which is the most recent combo:

BackendException: Could not initialize backend: cannot import name 'FileVersionInfoFactory' from 'b2sdk.file_version' (/usr/local/lib/p
ython3.9/dist-packages/b2sdk/file_version.py)

->  halt - no backup

hence I tried older versions in order to make it work:

b2 V 2.4 + b2sdk V 1.8:

Traceback (innermost last):
  File "/usr/bin/duplicity", line 122, in <module>
    with_tempdir(main)
  File "/usr/bin/duplicity", line 108, in with_tempdir
    fn()
  File "/usr/local/lib/python3.9/dist-packages/duplicity/dup_main.py", line 1529, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/local/lib/python3.9/dist-packages/duplicity/commandline.py", line 1217, in ProcessCommandLine
    backup, local_pathname = set_backend(args[0], args[1])
  File "/usr/local/lib/python3.9/dist-packages/duplicity/commandline.py", line 1088, in set_backend
    config.backend = backend.get_backend(bend)
  File "/usr/local/lib/python3.9/dist-packages/duplicity/backend.py", line 223, in get_backend
    obj = get_backend_object(url_string)
  File "/usr/local/lib/python3.9/dist-packages/duplicity/backend.py", line 209, in get_backend_object
    return factory(pu)
  File "/usr/local/lib/python3.9/dist-packages/duplicity/backends/b2backend.py", line 107, in __init__
    (self.path, bucket_name, self.service.account_info.get_minimum_part_size()), log.INFO)
 AttributeError: 'InMemoryAccountInfo' object has no attribute 'get_minimum_part_size'

also in this case : halt

b2 V 2.4 + b2sdk V 1.7:

Traceback (most recent call last):
  File "/usr/local/bin/b2", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/b2/console_tool.py", line 2023, in main
    exit_status = ct.run_command(sys.argv)
  File "/usr/local/lib/python3.9/dist-packages/b2/console_tool.py", line 1896, in run_command
    return command.run(args)
  File "/usr/local/lib/python3.9/dist-packages/b2/console_tool.py", line 537, in run
    return self.authorize(args.applicationKeyId, args.applicationKey, realm)
  File "/usr/local/lib/python3.9/dist-packages/b2/console_tool.py", line 551, in authorize
    self.api.authorize_account(realm, application_key_id, application_key)
  File "/usr/local/lib/python3.9/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/b2sdk/api.py", line 159, in authorize_account
    self.session.authorize_account(realm, application_key_id, application_key)
  File "/usr/local/lib/python3.9/dist-packages/b2sdk/session.py", line 117, in authorize_account
    self.account_info.set_auth_data(
  File "/usr/local/lib/python3.9/dist-packages/b2sdk/v1/account_info.py", line 30, in set_auth_data
    super().set_auth_data(
  File "/usr/local/lib/python3.9/dist-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/b2sdk/account_info/abstract.py", line 253, in set_auth_data
    self._set_auth_data(
  File "/usr/local/lib/python3.9/dist-packages/b2sdk/account_info/sqlite_account_info.py", line 236, in _set_auth_data
    conn.execute(
sqlite3.OperationalError: table account has no column named minimum_part_size

in this case : backup works, but warnings?

thanks

**Comment by ppolewicz** [comment] 2021-06-09 15:11
duplicate of https://github.com/Backblaze/b2-sdk-python/issues/251

**Closed** 2021-06-09 15:11 UTC
Labels: duplicate

**Comment by BHare1985** [comment] 2022-03-17 01:46
I just got this error when doing `apt-get install backblaze-b2`

What is the solution? Not use to Backblaze (lol)?

**Comment by ppolewicz** [comment] 2022-03-18 17:47
This is a duplicity bug, where they used our api in an unsupported way. You should probably install a new version of duplicity that resolves this issue.

**Comment by BHare1985** [comment] 2022-03-18 20:48
I didn't install duplicity though, I installed backblaze-b2 direct from the debian repository which is probably where duplicity gets it. 

I got around it by just install python and pip and doing `pip install b2` -- but someone should remove the debian rep or update it.
